### ISSUE TITLE
Issue running 'sudo composer update' during setup.

### ISSUE THREAD

**Issue by x-zempt** [zeropingheroes/lanager#77]
Was trying to setup a fresh Lanager install for a lan this weekend, but I am getting the below message when trying to update composer when following the install guide/instructions on a fresh server. When I setup this a couple months ago I didn't run into this issue.
I have tried Ubuntu 14.04 x86 & x64, both getting the same issue.

PHP Fatal error:  Class 'HieuLe\Active\ActiveServiceProvider' not found in /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'HieuLe\\Active\\ActiveServiceProvider' not found","file":"\/var\/www\/lanager\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":157}}Script php artisan clear-compiled handling the post-update-cmd event returned with an error

                                                                           
  [RuntimeException]                                                       
  Error Output: PHP Fatal error:  Class 'HieuLe\Active\ActiveServiceProvi  
  der' not found in /var/www/lanager/vendor/laravel/framework/src/Illumin  
  ate/Foundation/ProviderRepository.php on line 157

**Comment by azjose** [comment]
I had noticed this as well when I was trying to install another version as well. Has one of the dependency app changed up that would be causing this?

**Comment by ilumos** [comment]
Sorry chaps, should be fixed as of ca34661860858d57a6ea445b91b9232c7ccc41fc

**Comment by x-zempt** [comment]
Thanks for the prompt reply ilumos! Appreciate it!
After getting latest git release I get the below error. I tried troubleshooting myself, but I'm a bit of a PHP noob, lots to learn :D 

	Script php artisan clear-compiled handling the post-update-cmd event returned with an error                                                          
  [RuntimeException]                                                     
  Error Output: PHP Fatal error:  Class 'Zeropingheroes\Lanager\Command  
  s\Install' not found in /var/www/lanager/app/start/artisan.php on lin  
  e 14                                                                   
  PHP Fatal error:  Class 'Zeropingheroes\Lanager\Pages\Page' not found  
   in /var/www/lanager/app/composers.php on line 13

**Comment by ilumos** [comment]
Ok the fix is to rename `app/commands` to `app/Commands`

I'll commit the required changes shortly, but for now just do the above :)

**Comment by x-zempt** [comment]
Thanks mate! 
Looks like I have one more issue during the install, please see below.
I tried looking through the install.php file for some obvious issues, but I don't really know what I am looking for


2015-05-25 21:27:35 Testing requirements before installation...
2015-05-25 21:27:36 Checking PHP accessible in the system's path variable
2015-05-25 21:27:36 Passed
2015-05-25 21:27:36 Checking MySQL database accessible using the configured details
2015-05-25 21:27:36 Passed
2015-05-25 21:27:36 Checking Steam Web API key set
2015-05-25 21:27:36 Passed
2015-05-25 21:27:36 Checking Server able to access internet
2015-05-25 21:27:36 Passed
2015-05-25 21:27:37 Checking Steam Web API accessible with provided API key
2015-05-25 21:27:37 Passed
2015-05-25 21:27:37 All requirements passed - continuing with installation
2015-05-25 21:27:37 Creating database structure...
2015-05-25 21:27:37 Seeding database with example data...
PHP Fatal error:  Class 'Zeropingheroes\Lanager\Pages\Page' not found in /var/www/lanager/app/composers.php on line 13
PHP Fatal error:  Class 'Zeropingheroes\Lanager\Pages\Page' not found in /var/www/lanager/app/composers.php on line 13

**Comment by ilumos** [comment]
Should be fixed in adef8cec6fe9a86a308fc39b504e89fe33165b84

You'll probably hit some more errors - I've been refactoring loads of stuff recently... 

Once I've got everything stable I'll stop being a bad developer and branch off so as not to mess things up on the master branch.

**Comment by x-zempt** [comment]
Cheers.
Will go test it now :D

**Comment by x-zempt** [comment]
Appreciate all your hard work! Here is the next error during install.

2015-05-25 22:03:28 Testing requirements before installation...
2015-05-25 22:03:28 Checking PHP accessible in the system's path variable
2015-05-25 22:03:28 Passed
2015-05-25 22:03:28 Checking MySQL database accessible using the configured details
2015-05-25 22:03:28 Passed
2015-05-25 22:03:28 Checking Steam Web API key set
2015-05-25 22:03:28 Passed
2015-05-25 22:03:28 Checking Server able to access internet
2015-05-25 22:03:28 Passed
2015-05-25 22:03:29 Checking Steam Web API accessible with provided API key
2015-05-25 22:03:29 Passed
2015-05-25 22:03:29 All requirements passed - continuing with installation
2015-05-25 22:03:29 Creating database structure...
2015-05-25 22:03:29 Seeding database with example data...

[ReflectionException]
Class Zeropingheroes\Lanager\Seeds\DatabaseSeeder does not exist  
                                                                    
lanager:install

**Comment by ilumos** [comment]
Should be fixed in 8e1dd4cb111d73f67f62623f70448f95fbecfda5

Let me know how you get on

**Comment by x-zempt** [comment]
Next error is here, can't be many to go now :D


2015-05-25 22:22:28 Testing requirements before installation...
2015-05-25 22:22:28 Checking PHP accessible in the system's path variable
2015-05-25 22:22:28 Passed
2015-05-25 22:22:28 Checking MySQL database accessible using the configured details
2015-05-25 22:22:28 Passed
2015-05-25 22:22:28 Checking Steam Web API key set
2015-05-25 22:22:28 Passed
2015-05-25 22:22:28 Checking Server able to access internet
2015-05-25 22:22:28 Passed
2015-05-25 22:22:30 Checking Steam Web API accessible with provided API key
2015-05-25 22:22:30 Passed
2015-05-25 22:22:30 All requirements passed - continuing with installation
2015-05-25 22:22:30 Creating database structure...
2015-05-25 22:23:24 Seeding database with example data...


                                                                     
  [ErrorException]                                                   
  The use statement with non-compound name 'Eloquent' has no effect  
                                                                     


lanager:install

**Comment by ilumos** [comment]
Fixed in 3ef1b6e248679889f536d3a2ffaa16b8b87507dc

Hit me with the next one!

**Comment by x-zempt** [comment]
Looks like it has installed ok now, will let you know if I run into any other issues once loaded.
One quick question, which directory is the htaccess file with the AllowOverride meant to be in? The root  lanager folder or the public folder? 

Also, rename app/commands to app/Commands is still required, not sure if you missed this or planning on doing it later.

**Comment by ilumos** [comment]
Thanks :) 

I've fixed the app/commands issue in 28b8672ebfe690f980da39a1557ea446d59968f1

I've also commited some pretty extensive refactoring under the hood, so if you encounter any other errors, please do open an issue or three...
